### ISSUE TITLE
update_or_insert() method required

### ISSUE THREAD

**Issue by iwalu** [robinedwards/neomodel#108]
this user action is frequent  in practice. something like:
A user tries to tag an entity with existing tags, or provide a new one.

Besides, the method appears in py2neo however neomodel missed it.

**Comment by bleib1dj** [comment]
@Hexadite-Max I think you mentioned you were testing out py2neo's implementation of this using stream as @iwalu mentioned existed. Where you working on any functionality to integrate this directly with the `StructuredNode` class?

**Comment by Hexadite-Max** [comment]
Hi, yes. I have a working branch using py2neo over batch.stream with ```CypherJob```. This supports ```get_or_create()``` and ```get_or_create_bulk()``` class methods for the ```StructuredNode```. These use a ```CypherJob``` MERGE query, optionally when a relationship is specified it uses the CREATE UNIQUE query instead of MERGE; this ensures the uniqueness based on the relationship and not globally. 
I'll look into adding the "update" part, to set the non required properties as well, shouldn't be too much work. This is similar to https://github.com/robinedwards/neomodel/pull/167

**Comment by bleib1dj** [comment]
Great, thanks for the info! I believe @nigelsmall recommends using [Transactions](http://py2neo.org/2.0/cypher.html#transactions) over `CypherJobs` in the py2neo docs:
```
A Cypher execution job for inclusion within a batch. Consider using Cypher transactions instead of batched Cypher jobs.
```
I might be missing something but any particular reason on needing the `CypherJobs`?



Regarding ON MATCH/ON CREATE I believe you are correct, the only docs I know pertaining to it are the ones you've linked to and specifically [MERGE Relationships](http://neo4j.com/docs/stable/query-merge.html#_merge_relationships), where it indicates how you could use `MERGE` for relationships even though in CREATE UNIQUE docs it calls out:
```
MERGE might be what you want to use instead of CREATE UNIQUE. Note however, that MERGE doesn’t give as strong guarantees for relationships being unique.
```
I'm particularly interested in what the docs mean by "MERGE doesn’t give as strong guarantees for relationships being unique" when I thought `CREATE UNIQUE` was slated for deprecation as outlined in the [neo4j blog](http://neo4j.com/blog/new-milestone-release-neo4j-2-0-0-m03/) as well as [Graph Aware's blog](http://graphaware.com/neo4j/2014/07/31/cypher-merge-explained.html). So I would hope if MERGE is set to replace it, you would have the same guarantees... We should probably attempt to avoid using CREATE UNIQUE in favor of MERGE based on the articles but I'm not seeing a deprecation warning in the docs.

**Comment by Hexadite-Max** [comment]
So, I think I can do both:
- ```get_or_create()```, this is can be a class method of ```StructuredNode```, this method only works with required and unique properties.
- ```insert_or_update()```, this can be a class method of ```StructuredNode```; maybe create_or_update  is a better name to conform with existing ```create()```, this method will match on required/unique and update-or-insert any optional properties passed.

** both methods will use MERGE by default.
For get_or_create() I will add support for relationship to utilize CREATE UNIQUE

I went with CypherJob as it is the only way I have found to do batch statements and stream the results, although ```Transaction``` allows to append statements but does not allow to stream the results and returns all results on ```commit()```. I'll try to do some tests, but I assume this would be a performance hit as opposed to generate and inflate the results while streaming them back.

**Comment by bleib1dj** [comment]
Sounds like a plan and I'd vote for the `create_or_update`. Thanks for the help!

Gotcha thanks for the clarification! I'd be interested in hearing about the results if you don't mind sharing.

**Comment by Hexadite-Max** [comment]
@iwalu @bleib1dj please see https://github.com/robinedwards/neomodel/pull/176

All ```StructuredNode``` class methods: ```create()```, ```create_or_update()``` and ```get_or_create()``` now use the batch [Transaction](http://py2neo.org/2.0/cypher.html#transactions), following the minor benchmark I did, streaming was added as an optional feature, as it added no performance benefits and does not work with an active transaction.

Performance testing, I used the current ```create()``` call, and compared to ```create()``` using a batch and using streaming:

nodes | Original Create | Batch Create | Streaming Create
-------- | ------------------- | ----------------- | ----------------------
100 | 0.12s | 0.16s | 0.36s  
200 | 0.20s | 0.25s | 0.38s
500 | failed | 0.54s | 0.80s
1,000 | failed | 0.97s | 1.43s
10,000 | failed | 8.24s | 13.24s

These are not perfect, and I couldn't go over 200 nodes with original create, I assume as it is a single query and not 200 separate queries. **These were done on a dev machine and are more about the difference between the method rather the actual time.**

**Comment by bleib1dj** [comment]
Release 2.0.2 now has this integrated
