### ISSUE TITLE
Auto inflate

### ISSUE THREAD

**Issue by robinedwards** [robinedwards/neomodel#132]
Ability for a cypher query to auto inflate nodes based on their label

**Comment by bleib1dj** [comment]
I believe there is a list of labels associated with each node and they don't appear to be returned in any consistent order. What do you think we should do to support inflation of nodes that inherit from parent classes where both class names are set as labels on the node?

**Comment by robinedwards** [comment]
Yes I am not so sure how feasible this it relied on each node only having a single label which is quite brittle. I think this issue can be closed
