### ISSUE TITLE
query caching

### ISSUE THREAD

**Issue by robinedwards** [robinedwards/neomodel#134]
ability to cache queries

**Comment by bleib1dj** [comment]
What would this enhancement entail? Doesn't neo4j already manage [caching](http://neo4j.com/docs/stable/configuration-caches.html) internally?

**Comment by robinedwards** [comment]
Again I think this can be closed, it was for providing a system to cache results of expensive queries in a data store such as redis using a convenient decorator. I am not sure it belongs in the neomodel namespace so closing :+1:
