### ISSUE TITLE
Is there any prospect of support py2neo version 2.0.4?

### ISSUE THREAD

**Issue by SergeiIv** [robinedwards/neomodel#149]
May not apply to neomodel py2neo version above 1.6.4. Tell me, can project neomodel cast?

**Comment by robinedwards** [comment]
Hi @SergeiIv sorry for the delayed response, I've been very busy recently so I havent had chance to update neomodel. However I would gladly accept any patches, I can most likely help you out with any branch you get partially working

**Comment by sumit1001** [comment]
hi @robinedwards is there any release date of neomodel for supporting Py2neo 2.x version?

**Comment by bleib1dj** [comment]
@robinedwards I haven't looked into it much yet but what needs to happen to get neomodel up to 2.x and in particular 2.0.5? With Neo4j releasing 2.2 the other day this transition seems to be more and more important. I'd be willing to help out with the limited time I have. If it hasn't even been established as to what changes would need to be made we can at least start the conversation and start planning out the changes.

**Comment by bleib1dj** [comment]
So after some digging the closest thing I could find to an upgrade guide and release notes for the original 2.0 transition is this article http://neo4j.com/blog/py2neo-2-0-unleashed/. @robinedwards you'd know better than I if that is close to a full list of items that would be needed to make the transition. If we can open up a branch to make PRs to and create a milestone/tasks for each of these items we can get moving towards the integration. 

Based on Nigel Small's comments I'm not sure if you'd want to make a full version jump for this or attempt to make the system backwards compatible.

**Comment by robinedwards** [comment]
Hi,

Sorry not had much time to work on neomodel lately. The part of the code that needs updating is core.py all interactions with py2neo and neomodel occur in this file. There is some dubious monkey patching which would be nice to get rid of.

Whilst we are on the subject it maybe worth re-instating the __node__ attribute that returned the py2neo version of the node. I am more than happy to merge any PRs and help point you in the right direction.

**Comment by bleib1dj** [comment]
@robinedwards not a problem :). If you can open up a branch we can make pull requests to that doesn't affect master for the time being we can get started. Also if you wouldn't mind creating a milestone and assigning any issues you think would be useful outside of the baseline support that would be helpful. I'll open up tickets more specific to the necessary updates and we can formulate any necessary conversation around those.

**Comment by robinedwards** [comment]
https://github.com/robinedwards/neomodel/tree/py2neo_2_support

**Comment by robinedwards** [comment]
https://github.com/robinedwards/neomodel/milestones?with_issues=no

**Comment by bleib1dj** [comment]
Great thanks :)

**Comment by robinedwards** [comment]
@bleib1dj I have added you as a collaborator on this repo

**Comment by bleib1dj** [comment]
@robinedwards thanks that'll make it a bit easier :)

**Comment by nikbora** [comment]
Great work on pushing this @bleib1dj - it will be really useful for us to have py2neo 2 support. Let me know if can help in any way.

**Comment by bleib1dj** [comment]
@nikbora thanks! Will do, I'm still investigating what all needs to change based on @robinedwards advice but should have some more free time to really dive into it in the next few days so I can start getting tasks setup and get some PRs opened. I'll keep you posted if I run into any difficulties :).

**Comment by bleib1dj** [comment]
Closing this issue as continued discussion around support for py2neo 2.x should be had around PR #151 and issues associated with the milestone.
