### ISSUE TITLE
Documentation surrounding Neo4j 2.2.x requirements

### ISSUE THREAD

**Issue by bleib1dj** [robinedwards/neomodel#153]
With the release of Neo4j 2.2.2 there have been a few modifications to the initial install that require some additional tweaks from a developer to get up and going. To ensure ease of entry for new developers using neomodel we need to document these requirements and at least point the developers in the right direction. One known piece is authentication which is documented well by @nigelsmall in the [py2neo authentication docs](http://py2neo.org/2.0/essentials.html#authentication).

**Comment by bleib1dj** [comment]
@robinedwards Where would you like this documentation covered? I'm thinking about adding it into the README under a heading of something like `Transitioning from 1.x to 2.x` but didn't know if there would be a major version change for the release when the py2neo update branch is merged into master. Or I can start a new document under the docs area but I wasn't sure if it warranted a completely new doc.

**Comment by robinedwards** [comment]
I think all this brilliant work is definitely worth a version bump, perhaps call it 2.0. I think it would be nice if it lived in docs/ so its available on readthedocs

**Comment by bleib1dj** [comment]
Sweet :) and cool good point!
