### ISSUE TITLE
Issue in custom init while using get

### ISSUE THREAD

**Issue by siddharthm** [robinedwards/neomodel#160]
Since neomodel does not have any auto incrementing id, I decided to create an IntegerField called id and set its value to current count of that node class + 1. For this I overwrote the init class as in given example:

``` python
class NodeClass:
     id = neomodel.IntegerProperty()
     # more fields ...
     def __init__(self,*args,**kwargs):
          if id not in kwargs: 
              kwargs["id"] = len(NodeClass.nodes) + 1
          super(NodeClass,self).__init__(self,*args,**kwargs)

```

When I create a new instance of this NodeClass, everything is fine ( id is also set correctly).
But when I try to use the get method as 

``` python
NodeClass.nodes.get(id=123)
```

I get the following exception:

```
super(type, obj): obj must be an instance or subtype of type
```

P.S provided the code sample so just to make sure that I am not doing anything wrong instead of neomodel

**Comment by bleib1dj** [comment]
@siddharthm just as a note I'd recommend utilizing something like python's [UUID package](https://docs.python.org/2/library/uuid.html) to generate unique identifiers for nodes, it's a bit more scalable and doesn't run the risk of race conditions under load which this implementation may run into if a node hasn't been written to the database yet and the init method gets called. This will also cause a lot less querying to occur. To create your id you would do something along the lines of 

```
from uuid import uuid1

id = uuid1()
```

On another note if you do it this way you don't have to override init and can just set the function as the default parameter so it would look something like:

```
class NodeClass:
     id = neomodel.StringProperty(default=uuid1, unique_index=True)
```

On the exception I'll have to investigate further.

**Comment by siddharthm** [comment]
@bleib1dj You have been very helpful. Thanks a lot :)

**Comment by bleib1dj** [comment]
No problem :). Just to gather some more info, after updating the id field are you still seeing the exception being thrown?

**Comment by siddharthm** [comment]
No, not after removing init

**Comment by siddharthm** [comment]
@bleib1dj Is there some forum where I can post general queries?

My query is if I define a relationship on model A for model B do I need to always define a similar relationship in model B. Can't I access relationship with start node as B without having to write cypher query?

**Comment by robinedwards** [comment]
We could start a Google group?

**Comment by bleib1dj** [comment]
Either that or a [Gitter feed](https://gitter.im)

**Comment by bleib1dj** [comment]
@siddharthm We'll get something setup that we can discuss that and additional ongoing questions relating to the project.

@robinedwards do you know of a way to solve @siddharthm current question? I have a couple solutions that I'm not sure already exist within neomodel but am also unsure the performance repercussions of not indicating direction of the relationship (which may not matter in the use case).

**Comment by siddharthm** [comment]
@robinedwards @bleib1dj 
IMHO, Stackoverflow is best for this as it allows for better discoverability and has good reputation. Just that a few of us need to be active on it (Count me in). We can link to the neomodel [questions on SO](http://stackoverflow.com/questions/tagged/neomodel)  in neomodel's github page.

**Comment by bleib1dj** [comment]
@siddharthm I'm a larger fan of StackOverflow's layout and searchability as well. I think each of the forums have their place and I've started a conversation on #161 to discuss how we can better define those usages to new users.

**Comment by robinedwards** [comment]
id is also now used by neomodel v3 so i'd avoid using it as a property name
