### ISSUE TITLE
neomodel requires 'pytz==2014.7'

### ISSUE THREAD

**Issue by aalebedev** [robinedwards/neomodel#162]
Hi!

The latest version of pytz is 2015.4. Does neomodel have a close coupling with pytz?

**Comment by bleib1dj** [comment]
The package has been updated in the `py2neo_2_support` branch to 2015.4. The branch is still undergoing testing which is why it hasn't been merged into the master branch yet. There is some reliance but we can investigate removing the minor revision specification.

**Comment by robinedwards** [comment]
It's actually not used heavily and is only used to enforce UTC time stamps:

**Comment by robinedwards** [comment]
Relevant code can be found here: https://github.com/robinedwards/neomodel/blob/master/neomodel/properties.py#L243
