### ISSUE TITLE
Transactions with AsyncIO

### ISSUE THREAD

**Issue by corporatepiyush** [robinedwards/neomodel#165]
I wan to make use of this ORM lib with aiohttp( https://github.com/KeepSafe/aiohttp )
since there is only one thread which is doing everything (reactor pattern)
Are there any side effects from transaction point of view ?

**Comment by Hexadite-Max** [comment]
transactions are thread local, you will need to make sure you open and close your transaction before ```yield```. This is common to transaction handling, same goes to Django ORM etc.

**Comment by robinedwards** [comment]
I've fixed the above issue so theres no reason why this should not work, infact it should be a lot quicker now via bolt also. If you have any issues please re-open the issue
