### ISSUE TITLE
Reason structuredNode.save() returns it's self?  

### ISSUE THREAD

**Issue by ibigpapa** [robinedwards/neomodel#182]
I was just curious if there is a reason for the save method to return the object known as self and not update itself.  If there is a reason, should I be assigning the object to a variable instead of just calling save?

currently:
bb = Model()
bb.someproperty=somevalue
bb.save()

Should it be:
bb = Model()
bb.someproperty=somevalue
bb = bb.save()

**Comment by robinedwards** [comment]
The first example is just fine, the reason self is returned is to allow method chaining. I hope this answers your question

**Comment by ibigpapa** [comment]
Thanks  that'll do
