### ISSUE TITLE
Support matching on regular expressions?

### ISSUE THREAD

**Issue by midnightlynx** [robinedwards/neomodel#183]
Per the Neo4j documentation, WHERE clauses in a query can filter on a regular expression match.
http://neo4j.com/docs/2.0.5/query-where.html#_regular_expressions

If neomodel currently supports these, it's not documented.
If not, could that support be added in a future release?

**Comment by Hexadite-Max** [comment]
Hi, current release 2.0.2 supports all regex queries see the updated docs here https://github.com/robinedwards/neomodel/blob/master/doc/source/queries.rst#node-sets-and-filtering
