### ISSUE TITLE
"db_name" parameter for Property

### ISSUE THREAD

**Issue by fpieper** [robinedwards/neomodel#185]
Is it possible to use db_name (or something else ;) ) for Property? Or is it already builtin? 

```
name = StringProperty(required=True, db_name="full_name")
```

Or is it possible to achieve this behaviour with a workaround?

Otherwise I would integrate the functionality and make a pull request. I analyzed the code already and found the following positions to integrate "db_name".

```
in core.py: create, get_or_create, create_or_update => use correct label
in match.py: process_filter_args => add label to output tuple, build_where_stmt => get label and build correct query
```

Any thoughts?

**Comment by fpieper** [comment]
I solved the problem and integrated "db_property". I pushed it as the Pull request #186

**Comment by robinedwards** [comment]
Super thats been merged now, closing
