### ISSUE TITLE
possible redundant cypher query on connect with properties

### ISSUE THREAD

**Issue by Hexadite-Max** [robinedwards/neomodel#187]
Hi,

I noticed that a call to `connect()` with properties has two calls to execute cypher query, I think https://github.com/robinedwards/neomodel/blob/master/neomodel/relationship_manager.py#L94 is redundant and has no affect after https://github.com/robinedwards/neomodel/blob/master/neomodel/relationship_manager.py#L92

**Comment by robinedwards** [comment]
Good spot!

**Comment by robinedwards** [comment]
Fixed
