### ISSUE TITLE
create_or_update breaks in neo4j 2.0

### ISSUE THREAD

**Issue by midnightlynx** [robinedwards/neomodel#190]
> InvalidSyntax: Invalid input '+': expected whitespace, comment, node labels, MapLiteral, a parameter, a relationship pattern, '(', '.' or '=' (line 4, column 17)
> "`ON MATCH SET n += params.update`"

Cypher syntax in Neo4j 2.0 didn't have the `+=` operator.

**Comment by Hexadite-Max** [comment]
you are correct `+=` notation is available starting with [v2.1.8 set-adding-properties-from-maps](http://neo4j.com/docs/2.1.8/query-set.html#set-adding-properties-from-maps)

This means we can't run `create_or_update()` on neo4j < 2.1.8 :disappointed: 

@robinedwards @bleib1dj thoughts?

**Comment by bleib1dj** [comment]
@robinedwards @Hexadite-Max how far back are we looking to support? I'd be happy to merge something in that provides backwards compatibility but since we're already up to 2.3.1 and 3.0.0 just had it's first beta release not sure where the line on backwards compatibility should be drawn.

**Comment by robinedwards** [comment]
Hi sorry about this and the some what delayed response, I've updated master to require neo4j 3 so I am closing this issue.
