### ISSUE TITLE
Node Caching Inconsistencies

### ISSUE THREAD

**Issue by bleib1dj** [robinedwards/neomodel#191]
This may be an issue with py2neo rather than neomodel but thought I'd start the conversation here and have a tracker.

I'm seeing it in Django but any multi threaded environment should have the same result. So this may have to do with #165.

What's occurring is I have an existing node that I update in one worker and then from the django shell I attempt to access the updated value. If I query the node prior to the update and then again after the update the Node remains the same and the update is not properly represented. I've tried utilizing transactions in the shell but until I exit the shell, releasing all of the objects, re-enter it, and query again I can't get the updated node. 

I've tried:

```
with neomodel.db.transaction:
    res, _ = neomodel.db.cypher_query(query)
print res.one

with neomodel.db.transaction:
    content = Content.nodes.get(uuid="some uuid")
print content

content = Content.nodes.get(uuid="some uuid")
content.refresh()
print content
```

And a varying mixups of these as well as creating new Database instances and py2neo Graph instances. I was looking into it and it looks like py2neo caches off Nodes and Relationships in the Graph instance which may be why until I exit the shell or a worker dies it continues to get the same stale data upon a query.

**Comment by bleib1dj** [comment]
@robinedwards @Hexadite-Max ever experienced this?

**Comment by bleib1dj** [comment]
Also found that if I do use py2neo's Graph and do:

    graph.cypher.execute('enter query for node').one.pull()

then do

    graph.cypher.execute('enter query for node').one

the node get's updated correctly.

**Comment by bleib1dj** [comment]
So the current work around looks something like:

    results = []
    res, _ = db.cypher_query("some query") # Doesn't actually query db unless Node doesn't exist
    for row in res:
        row[0].pull() # Queries DB for all nodes in list
        results.append(row[0])
    return results

**Comment by robinedwards** [comment]
neomodel 2 wasn't process safe, it would share connections between processes which resulted in unexpected results. This is now fixed in master (with tests).
