### ISSUE TITLE
Make connection to database more flexible

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#192]
AFAICT the only way to set the graph database URL is by setting an environment variable which is used by Neomodel at import time. This is awkward when one wants to use a config file to select a database. 

For example: I'm creating a Flask application that uses an application factory that selects one from several sets of configuration (one for testing, one for development, one for production). One of the settings (in each set) is the URL for the graph database. This is a common Flask pattern. 

As it stands I cannot set the graph database URL using this scheme because Neomodel: 
1) only uses an env. variable 
2) uses this env variable at import time (ie when the neomodel user classes are defined, eg class Country(StructuredNode)).

So this is done by Neomodel before I can call my App factory, and therefore before I can set the URL.

**Comment by robinedwards** [comment]
This is a good point and needs addressing, the environment config dates back to the libraries early development where I was deploying on Heroku. Perhaps we need a connect function that the we export, then projects such as https://github.com/neomodel/neomodel-django can call this internally.

**Comment by mjmare** [comment]
That would be useful. 
A complication might be that model class definitions (derived from StructuredNode) seem to access the graph database.

**Comment by kaplun** [comment]
Indeed such functionality would be great to ease deployment and configuration.

**Comment by nkoester** [comment]
I also just ran into exactly this issue in my project. A more sophisticated connection handling would be greatly appreciated! I would propose to have a connection handler or a class handling the connection.

**Comment by robinedwards** [comment]
This is now implemented in master
