### ISSUE TITLE
Make it easier to find 1 node (or None)

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#194]
AFAICT it is not very easy to find a node. Currently the way to find a node is to use SomeModel.nodes.get(kwargs), but that might throw an exception. I'd prefer a method that returns either the node found or None. 
I cannot use SomeModel.nodes.filter because there is no "eq" filter method.

**Comment by robinedwards** [comment]
You don't need an __eq as it defaults to that so this should work:
 
```python
person = People.nodes.filter(name='Tim')
```

**Comment by mjmare** [comment]
Cool. Did I miss this in the docs? If not, maybe add this to the docs?
