### ISSUE TITLE
Advanced label manipulation

### ISSUE THREAD

**Issue by bebbi** [robinedwards/neomodel#195]
Hi, I'm just migrating from 1.9 to 2.x.
I was wondering if there's any mechanism for label manipulation similar to what was introduced in #55 for indices?
The way I understand it, neomodel creates 1 class : 1 label relationships. If so, is there any API level functionality for going beyond that like sharing labels across inherited classes?
(And maybe custom/multiple labels per node?)
Thanks!

**Comment by bebbi** [comment]
Just figured out that inherited classes will create labels of class name, and super class name, and names of other multiply inherited StructuredNode class names. That's quite nice, and probably addresses my use-case.
Maybe something to add to the docs, unless I missed that piece.

**Comment by bebbi** [comment]
OK, I guess there are some aspects where it might be nice to have a better understanding when using inheritance on StructuredNodes:
For example, I am connecting a few other_nodes to "topnode" with the same relation. other_nodes all share the same base_class but may or may not be inherited beyond that.

Now, since the inflate class appears to be defined by the RelationshipTo/From attribute, on retrieving topnode.other_nodes.all() I will inflate all results with base_class even if they are inherited.

I think that's ok if:
- is there a simple way to deflate an instance and inflate it again with a different class (avoiding a db roundtrip)?

- is there a way of knowing the inherited class of the inflated base node?

For latter, I suspect that given the logic that neo4j orders labels by order of creation (internal label id), and how neomodel appears to work, the highest-level class probably always ends up being the last label, I wonder if that is correct?

Hope that makes sense..

**Comment by the4thv** [comment]
@bebbi, you can certainly do the first question if you create a custom method in the class to do it; thus:

```
class LabelA (StructuredNode):
    <properties>
    <relationships>

    def methodA (self):
        ...
        try:
            return [<node_class>.inflate(row[0]) for row in results]
        except AttributeError:
            return []
        except Exception as e:
            raise e
```

Where <node_class> could be another class you've defined. I only use this when I need to return the result NodeClass from a different class.

For the second point, I'm not sure what you are wanting to do, but it sounds like you are wanting to create a relationshipTo/From that is generic to more than one other node class. Where I have needed something similar, I have used a custom method.

I hope that helps!

**Comment by robinedwards** [comment]
@bebbi 

"Now, since the inflate class appears to be defined by the RelationshipTo/From attribute, on retrieving topnode.other_nodes.all() I will inflate all results with base_class even if they are inherited."

This is no longer correct since neomodel 2, its based on the label as opposed to the incoming relationship.

"is there a way of knowing the inherited class of the inflated base node?"

Yea you can do this in python using the __bases__ attribute or `inspect.getmro(cls)`.

Closing but feel free to reopen if you have any more questions
