### ISSUE TITLE
Provide a way to query by node id

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#199]
I'm trying to implement support for Flask-Admin. I have to query by id. 
I was hoping for something like: 

person1=Person.nodes.filter(id=167)

but that throws an exception that the property doesn't exist (which is technically correct I suppose). 

I have to resort to something like this:

query = "MATCH (a) WHERE ID(a)={id} RETURN a"
results, meta = db.cypher_query(query, dict(id=167))
p2 = Person.inflate(results.one) if results.one else None

Or am I overlooking something?

**Comment by Hexadite-Max** [comment]
you are correct regarding  a better way to do it, for now I can suggest this workaround if you'd rather not write your own CYPHER (this does exactly what you wrote..)
```
person = Person(_id=167)
person.refresh()
```

**Comment by mjmare** [comment]
Ah I see, you're using refresh to 'get' the object. But that would work with this specific use case, ie getting the object by id. The more general case being filtering object by non NeoModel properties. 
The workaround is fine by me for now, thx.

**Comment by aanastasiou** [comment]
@SimaDovakin Try `neomodel.db.cypher_query("MATCH (a:YourLabels)) WHERE id(a) == TheNodeId return a", resolve_objects=True)[0][0][0]`

The `[0][0][0]` is required due to the way the results are returned from `cypher_query`.

**Comment by aanastasiou** [comment]
@SimaDovakin No worries, glad you found this helpful. Please use the "Discussions" feature for similar questions in the future. I happened to catch this but because it was put in a closed issue, it might sleep our attention.
