### ISSUE TITLE
Custom __init__ does not work

### ISSUE THREAD

**Issue by patently-offensive** [robinedwards/neomodel#202]
I'm trying to set up some simple functionality, where I create new nodes based on model instances using a post_save signal receiver. To make this clean, I want to implement a custom **init** that simply takes the post_save instance. I can't get amu custom **init** to work, even the example provided in the documentation. They all fail with a RequiredProperty exception.

Here's what I originally created:

```
class ProductNode(StructuredNode):
    uid = StringProperty(unique_index=True, required=True)
    name = StringProperty(default='NO PRODUCT NAME PROVIDED!')

    company = RelationshipFrom('CompanyNode', 'SELLS')

    def __init__(self, product, *args, **kwargs):
        self.product = product
        self.uid = 'g.' + str(self.product.pk)
        self.name = self.product.product_name

        super().__init__(self, *args, **kwargs)
```

And I'm initializing via this signal handler:

```
@receiver(signals.post_save)
def graphify(sender, instance, **kwargs):
    m = sender.__name__
    i = instance

    if m == [...]
    elif m == 'Product':
        p = ProductNode(i)
        p.save()
```

Which results in this exception when I create a new product in the django admin interface:

> raise RequiredProperty(key, cls)
> neomodel.exception.RequiredProperty: property 'uid' on objects of class ProductNode

If I put a pdb.set_trace() right before the super() call, I can see that self.product, self.uid, and self.name are all set properly. 

I've even tried this alternative version, which is identical to the example in the documentation and only takes string arguments instead of a model instance. Same result:

```
class T_ProductNode(StructuredNode):
    uid = StringProperty(unique_index=True, required=True)
    name = StringProperty(default='NO PRODUCT NAME PROVIDED!')

    def __init__(self, uid, name, *args, **kwargs):
        self.uid = uid
        self.name = name

        super().__init__(self, *args, **kwargs)
```

I've also tried the exact example [from the documentation](https://neomodel.readthedocs.org/en/latest/extending.html) and I get the exact same exception, but with respect to the 'name' unique index:

```
class Person(StructuredNode):
    name = StringProperty(unique_index=True)

    def __init__(self, name, *args, **kwargs):
        self.name = name

        super(Person, self).__init__(self, *args, **kwargs)
```

**Comment by Hexadite-Max** [comment]
this is a doc bug, all properties are overridden in the `super().__init__()` call. you can simply pass the new values to the super as kwargs (StructureNode does nothing with *args btw)  :
```
def __init__(self, product, *args, **kwargs):
        self.product = product
        kwargs["uid"] = 'g.' + str(self.product.pk)
        kwargs["name"] = self.product.product_name

        super().__init__(self, *args, **kwargs)
```

**Comment by robinedwards** [comment]
Good spot i've just added docs for this
