### ISSUE TITLE
Django model style repr

### ISSUE THREAD

**Issue by mixxorz** [robinedwards/neomodel#205]
What if we implement a `__repr__` method on StructuredNode? (Or a deeper base class)

We could make our nodes look like

```
<MyNode: Something>
```

Where 'Something' comes from the implementing class' `__str__` method. Basically how Django models work. It'll make for easier debugging.

If you're cool with this idea, I'll happily submit a PR for this. I'd like suggestions on what class I should put it on though.

**Comment by g3rd** [comment]
I actually did this for my abstract node class.
