### ISSUE TITLE
Connections during import time makes testing hard

### ISSUE THREAD

**Issue by mixxorz** [robinedwards/neomodel#207]
During testing, it's ideal that a Neo4j server is not required for the tests to pass. Neomodel makes this really hard by requiring the server during import time.

Is there any way to work around or disable this feature?

**Comment by mixxorz** [comment]
I've worked around the issue by monkey patching `core.install_labels' in my test module before importing any neomodel references.

```python
# Monkey patch install_labels to disable connecting to Neo4j during import time
# in tests
def patch_install_labels(cls):
    pass

core.install_labels = patch_install_labels
```

**Comment by robinedwards** [comment]
I've added a setting for this https://github.com/robinedwards/neomodel/tree/master/doc/source
