### ISSUE TITLE
Successive relationship match problems

### ISSUE THREAD

**Issue by midnightlynx** [robinedwards/neomodel#208]
Say I have a StructuredNode `foo`, with a StructuredRel 'bar'.
When I perform `foo.bar.match(name='baz').all()`, `match` appends a filter to `foo.filters`.

That filter sticks around over the life of `foo`, so if I later call `foo.bar.match(name='zot').all()` for a different reason, it now has two mutually exclusive filters and turns up nothing.

Similar problems exist with `foo.bar[x:y]` or `foo.bar[x]` setting `foo.skip` and `foo.limit`, also affecting all future searches through the relationship during `foo`'s lifetime.

This isn't really expected or documented behavior. Once results are actually fetched, it's not really intuitive to think remnants of that search's constraints will linger to effect future searches. Initializing a whole new node object for successive searches sounds inefficient, and manually resetting those internal attributes sounds ugly.

Possible fixes:
- Provide a method on RelationshipManager to reset those variables, and document the use & reason for it. (Quick & dirty, user error can still be a problem)
- Modify the RelationshipManager's `.all()` method (and other methods that return actual results instead of modifying and returning itself) to also clear these attributes. (A little more thorough & consistent)
- Modify the `QueryBuilder` so that it clears these attributes somewhere in the process of building & sending the cypher query. After `.build_ast` does its work, or after `._count`/`._execute` send the constructed query would make sense. (I'd prefer a fix at this level, personally.)

**Comment by the4thv** [comment]
@midnightlynx, I also had this. I assume this is how @robinedwards intended, because you can use: 

- .filters (to list applied filters which, as you say stick around)
- .filters.clear() (clears all of them)
- filters.remove(value) - but the filters are a list of dicts and value == the dict you want to remove.
