### ISSUE TITLE
Support to the new neo4j python driver

### ISSUE THREAD

**Issue by pdonorio** [robinedwards/neomodel#209]
With the official release of neo4j 3, there is a new python native driver.
http://neo4j.com/blog/neo4j-3-0-massive-scale-developer-productivity/

> To complement Bolt, we’re releasing official language drivers which encapsulate the protocol, freeing contributors to focus on unique language and framework integration. The new official language drivers include:
> JavaScript
> Python
> Java
> .NET

Are there any plan to support it?
The project is available here:
https://github.com/neo4j/neo4j-python-driver

**Comment by the4thv** [comment]
hi @pdonorio, I've been in conversation with @robinedwards and my colleague and I going to commence work on this, which will be moderated by @nigelsmall (the author of py2neo). I will be commencing the work this week. (Robin is currently away.)

Kind Regards,

Dave

**Comment by pdonorio** [comment]
That's very great new @the4thv!
Please, let me also know if i may help in some way

**Comment by the4thv** [comment]
Thanks :) & will do. I'll be sitting down with my colleague tomorrow/Thursday to plan it, so I'll get back to you then.

**Comment by pdonorio** [comment]
FYI I just updated today with pip to latest versions of Python library.
I ended up with py2neo 3.0, and it seems like the latest neomodel doesn't handle it:


```bash
# run a small alpine docker image with python3 + pip
docker run --rm -it eudatb2safe/apiclient ash
$ pip install py2neo neomodel
$ python3 -c "import neomodel"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/neomodel/__init__.py", line 2, in <module>
    from .core import *
  File "/usr/lib/python3.5/site-packages/neomodel/core.py", line 3, in <module>
    from py2neo.cypher.error.schema import (IndexAlreadyExists,
ImportError: No module named 'py2neo.cypher'

```

while specifying the old 2.0.8 release:

```bash
docker run --rm -it eudatb2safe/apiclient ash
$ pip install py2neo==2.0.8 neomodel
$ python3 -c "import neomodel"

# no problems
```

Maybe py2neo == 2.0.8 should be a requirement?

Should i open an issue or is it already tracked?

Thanks

**Comment by phoebebright** [comment]
Great news neomodel is being updated for neo4j 3.  Happy to test when the time comes.

**Comment by atharvai** [comment]
Any ETA on neo4j 3.x compatibility?

**Comment by the4thv** [comment]
Hi @atharvai, sorry for the delay, it's in the works. I will update this thread with an ETA early next week.

**Comment by atharvai** [comment]
Great thanks. Looking forward to it!

**Comment by the4thv** [comment]
Hi All,
There's quite a lot of difference in py2neo3, so I don't expect to be finished with my alpha for 3 weeks, then I'll submit it to Nigel. I'll try and add an update once a week (at the weekend).

Thanks,

Dave

**Comment by robinedwards** [comment]
Sorry for the delay on this, I've just pushed to master a branch based on the neo4j_driver. It's not ready for pypi yet but i'd appreciate some feedback before I make a release in the next week or so
