### ISSUE TITLE
Neomodel behavior not process-safe

### ISSUE THREAD

**Issue by midnightlynx** [robinedwards/neomodel#210]
Using neomodel in a multi-process environment, such as with [Celery](http://www.celeryproject.org/), it displays some odd behavior. Method calls seem to be retrieving the results of DB queries sent by other method calls.

Minimal-ish example:
- python 3.4.3
- py2neo 2.0.7
- neomodel 2.0.2
- neo4j 2.3.3

example.py:

```
import neomodel
from celery import Celery

app = Celery('example', broker='amqp://')


class Thing(neomodel.StructuredNode):
    name = neomodel.StringProperty(unique_index=True, required=True)


@app.task(name='thing.create', ignore_result=True)
def make_thing(name=''):
    thing, = Thing.get_or_create({'name': name})
    if thing.name != name:
        print('bad_thing found={} expected={}'.format(thing.name, name))

of 
if __name__ == '__main__':
    for i in range(32):
        make_thing.delay(name=str(i))
    print('test batch sent')
```

Usage:
- In a command line prompt, enter `python example.py`. That will queue up a fair amount of asynchronous tasks.
- enter `celery worker -A example`. That starts up a celery worker with multiple worker processes, that retrieves and runs the asynchronous tasks.
- Starting the worker with tasks already queued seems to better the chance of hitting the 'right' race conditions to reproduce the bug, as does starting with an empty neo4j DB.

Upon starting the celery worker, you should see some number of log lines on the console indicating tasks where the node retrieved is not actually the one that was queried for.

**Comment by midnightlynx** [comment]
By comparison, using py2neo directly instead of through neomodel:
```
from celery import Celery
from py2neo import Graph

app = Celery('example', broker='amqp://')
graph = Graph()


@app.task(name='node.create', ignore_result=True)
def make_node(name=''):
    thing = graph.merge_one('Thing', 'name', name)
    if thing['name'] != name:
        print('bad_node found={} expected={}'.format(thing['name'], name))


if __name__ == '__main__':
    for i in range(32):
        make_node.delay(name=str(i))
    print('test batch sent')
```
This doesn't show the same behavior.

Interesting finding... if the file also imports neomodel and subclasses `StructuredNode`, then the tasks get anomalous results even when retrieving the nodes through the `py2neo.Graph` instance directly.

**Comment by ryantam626** [comment]
Ran into the same issue using multiprocessing lib. Got the same behaviour as @midnightlynx. 

Here is a simple example to try to understand what is going on under the hood. 

    from py2neo import Graph

    import logging 

    logger = logging.getLogger()
    fileHandler = logging.FileHandler('logs')
    fmt = '%(asctime)s %(processName)-10s [%(name)s] %(levelname)-8s %(message)s'
    datefmt = '%m-%d %H:%M:%S'    
    formatter = logging.Formatter(fmt, datefmt)
    fileHandler.setFormatter(formatter)

    logger.addHandler(fileHandler)
    logger.setLevel(10)

    graph = Graph("http://neo4j:neo4j@localhost:7474/db/data/")

    ## graph merge one 
    for thing_id in range(3):
        graph.merge_one('thing', 'name', 'youwotm{}'.format(thing_id))

        ## this uses something of the sort:-
        ## execute 'MERGE (n:thing {name:{V}}) RETURN n,labels(n) LIMIT 1' {'V': 'youwotm0'}

    import neomodel

    class Thing(neomodel.StructuredNode):
        name = neomodel.StringProperty(unique_index=True, required=True)

        @classmethod
        def get_or_create_test(cls, *props, **kwargs):

            lazy = kwargs.get('lazy', False)
            relationship = kwargs.get('relationship')

            # build merge query
            get_or_create_params = [{"create": cls.deflate(p, skip_empty=True)} for p in props]
            query, params = cls._build_merge_query(get_or_create_params, relationship=relationship, lazy=lazy)

            return query, params

    ## neomodel's get_or_create
    for thing_id in range(3):
        Thing.get_or_create({'name':'youwotm{}'.format(thing_id)})

        ## this uses something of the sort:-
        ## begin
        ## append 'UNWIND {merge_params} as params\n MERGE (n:Thing {name: params.create.name})\n ON CREATE SET n = params.create\n RETURN n' {'merge_params': [{'create': {'name': 'youwotm2'}}]}
        ## commit 



Could this be due to the difference between begin > append > commit vs execute?

**Comment by ryantam626** [comment]
Hey @midnightlynx,

I think moving the class definition into the celery task solves that. Not sure how to word it, but I am guessing by defining `Thing` outside (ie. not in `make_thing`), celery (or in my case multiprocessing) failed to play well with neomodel's `Database` which inherited `threading.local`, which means that transactions will be messed up. [Also, using threading instead of multiprocessing solved my issues.]

I think doing an import for `Thing` within the celery task should work too? (I can't get the import to work though, maybe you can get around it?)

**Comment by robinedwards** [comment]
Thanks for the report, I will look into this in the up and coming week before releasing to pypi
