### ISSUE TITLE
Random ordering

### ISSUE THREAD

**Issue by romaintha** [robinedwards/neomodel#214]
Hi,
I would like to implement the random ordering for neomodel, similar to Django order_by("?"). I found this regarding Cypher :
http://jexp.de/blog/2014/03/random-thoughts-ordering-in-cypher/
I have a very limited insight of neomodel, but it does not seem easy to implement. Any suggestions where to start?

**Comment by romaintha** [comment]
Hi @the4thv ,
I do agree that the generated load might become a problem. But I guess it would be great to have the possibility to do it, and the performance consideration would be let to anyone using it.
I envisioned the solution you proposed. But I was thinking to mimic as much as possible the django order_by("?").  As far as I see the NodeSet class of neomodel, using order_by(prop) checks that prop is indeed a property.  So there would be a need to rework that. In addition looking at the QueryBuilder class, and how the order_by query is built, it seems complicated to implement here the method I attached previously. 
What do you think?

**Comment by the4thv** [comment]
@romaintha , yes. I'm actually working on neomodel for Neo4j 3.0 with Robin's blessing and I'd be happy to implement your proposal in that. I'm reworking the basic logic to bring it more inline with new Neo4j cypher, including the QueryBuilder. It won't be too hard for me to take into consideration adding support for this.

**Comment by romaintha** [comment]
@the4thv then I ll work on that and let you know when I have a proposal

**Comment by the4thv** [comment]
@romaintha cool - thanks :)

**Comment by the4thv** [comment]
Thank you for your proposal. I'll look to implement that in the new alpha version of neomodel and we can review how it works with Neo4j.

**Comment by robinedwards** [comment]
Merged thanks ever so much :-)
