### ISSUE TITLE
Issue with connecting models of same class

### ISSUE THREAD

**Issue by ahrennsiva** [robinedwards/neomodel#216]
Essentially trying to connect two nodes of the same type, as the first step in recommending users to follow through users currently followed. I'm running into this problem: isinstance() arg 2 must be a class, type, or tuple of classes and types.

Any advice for how I can build this functionality in neomodel or why i'm hitting this error would be great.

This is what the class looks like so far:
class NeoConnectProfile(StructuredNode):
    user_id = IntegerProperty(required=False, unique_index=True)
    company= StringProperty(required=False, index=True)
    following = RelationshipTo('NeoConnectProfile', 'FOLLOW')
    followers = RelationshipFrom('NeoConnectProfile', 'FOLLOW')

```
def follow_person(self, user_id):
    followed_user = self.index.get(user_id=user_id)        
    self.follow.connect(followed_user)        

def unfollow_person(self, user_id):
    followed_user = self.index.get(user_id=user_id)
    self.follow.disconnect(followed_user)
```

**Comment by the4thv** [comment]
Hi @ahrennsiva, is there a reason why you don't want to just use:
`ncp1.following.connect(ncp2)`
and/or
`ncp1.followers.connect(ncp2)`
where ncp1 and ncp2 are two nodes of the NeoConnectProfile? This would achieve the same end state as your custom methods without needing to extend the Class.

**Comment by robinedwards** [comment]
You are also using index which is deprecated and has now been removed in master. If @the4thv doesn't solve your problem please re-open the ticket
