### ISSUE TITLE
Upgrading to neomodel for neo4j 3.0

### ISSUE THREAD

**Issue by siddharthm** [robinedwards/neomodel#220]
Hi,
I am using neo4j 3.1 with latest neomodel. Earlier I used to use it with 2.3.x. I saw that neomodel now uses id property to hold the neo4j internal id. So I had to change that for every model.

Now when I try a relationship's get method I get a cypher error due to an empty where clause when I try r.owner.get()

`CypherError: Invalid input 'w': expected 'r/R' or 'p/P' (line 1, column 126 (offset: 125))
"START r = node({r_1}) MATCH ((r)-[r1:OWNED_BY]->(owner:F)) WHERE  RETURN owner LIMIT 2"`

This issue is there for every get method invocation. I checked the latest neomodel docs and found no mention of the get method. So is it removed or there is some other bug? Also what other changes have been made during upgrade to neo4j 3

Thanks,
Siddharth

**Comment by siddharthm** [comment]
I have create a pull request to fix this bug  
https://github.com/robinedwards/neomodel/pull/221
cc @robinedwards

**Comment by robinedwards** [comment]
Hey, thanks for spotting and fixing the bug. Releasing to pypi today.

All changes should be present in the Changelog: https://github.com/robinedwards/neomodel/blob/master/Changelog

regarding the id property change, the old property _id still exists its just deprecated. I hoped that your code would stil work calling _id was this not the case?

**Comment by robinedwards** [comment]
3.0.1 is now on pypi

**Comment by siddharthm** [comment]
@robinedwards oh no, we had an id field already in use and had to rename it now. we were not using _id. Just a question, why was this change (i.e to use id for neo4j id) instituted? Because if I am not wrong neo4j now reuses old ids so any case we can't use the id for anything permanent or outside facing.

**Comment by robinedwards** [comment]
Ah i see terribly sorry about that.

I noticed the neo4j driver and py2neo were doing it and it just seemed like a cleaner api, you are correct thought it shouldn't be used for anything outside facing.
