### ISSUE TITLE
Deadlock in gunicorn multi workers

### ISSUE THREAD

**Issue by siddharthm** [robinedwards/neomodel#222]
Hello,

when trying to use neomodel with gunicorn multiple workers I get a deadlock error many a times and the workers shut down:

```
  File "/webapps/env/local/lib/python2.7/site-packages/neomodel/core.py", line 58, in __new__
    install_labels(inst)
  File "/webapps/env/local/lib/python2.7/site-packages/neomodel/core.py", line 20, in install_labels
    cls.__label__, key))
  File "/webapps/env/local/lib/python2.7/site-packages/neomodel/util.py", line 28, in wrapper
    return func(self, *args, **kwargs)
  File "/webapps/env/local/lib/python2.7/site-packages/neomodel/util.py", line 110, in cypher_query
    raise exc_info[1]
CypherError: ForsetiClient[4] can't acquire UpdateLock{objectId=581755225, refCount=2, holder=ForsetiClient[3]} on SCHEMA(0), because holders of that lock are waiting for ForsetiClient[4].
 Wait list:SharedLock[
Client[3] waits for [],
Client[4] waits for [3]]
 
```

Additionally when killing the worker(s) I get this message, this is a separate issue:

`TypeError: "'NoneType' object is not callable" in <bound method Connection.__del__ of <neo4j.v1.connection.Connection object at 0x7f154c8c74d0>> ignored
`

@robinedwards if you could provide some pointers, I'll try to fix the issue.

**Comment by robinedwards** [comment]
Ok for the first part try disabling automatic label creation:

http://neomodel.readthedocs.io/en/latest/configuration.html#disable-automatic-index-and-constraint-creation

I need a better solution for this, perhaps I need to remove it and make it a command users have to call when they update their schema?

The last issue comes from neo4j_driver I ran into it a few times whilst working on neomodel, try putting a breakpoint in here: https://github.com/robinedwards/neomodel/blob/master/neomodel/util.py#L96 and running it through the debugger it may give you some more options.

**Comment by siddharthm** [comment]
@robinedwards thanks for the first thing. It worked. But had to run a single worker first to install labels for the first time. A manual method would be good. Also never faced this issue in neo4j 2.3 so something new here?

Regarding the 2nd issue, will check

**Comment by robinedwards** [comment]
You can call it manually,  theres docs here:

http://neomodel.readthedocs.io/en/latest/configuration.html#disable-automatic-index-and-constraint-creation

You could build this into your deployment mechanism.

Nothing has changed, the label install has always been there. However
perhaps the connection method causes the deadlock.

**Comment by robinedwards** [comment]
@siddharthm I am going to add a not about gunicorn to the docs do you mind if I close this issue?

**Comment by siddharthm** [comment]
@robinedwards sure
