### ISSUE TITLE
relationships: multiple relationships of same type between nodes

### ISSUE THREAD

**Issue by eamonnmag** [robinedwards/neomodel#223]
Is it possible within neomodel to create multiple relationships of the same type, but with different properties in neomodel. e.g.

e.g. suppose I had a date range attached to a relationship, or the position they had
JOHN - [WORKS_AT (from 2015 to 2016)] -> Walmart
JOHN - [WORKS_AT (from 2013 to 2015)] -> Bestbuy

In neomodel, this seems not possible at present. I thought we'd get around it through some unique property on the relationship, but that seems to not work either.

**Comment by robinedwards** [comment]
It is possible there are structured relationships which would allow you to define a 'from' property on the 'WORKS_AT' rel:

http://neomodel.readthedocs.io/en/latest/relationships.html#properties

I hope this answers your question?

**Comment by eamonnmag** [comment]
We tried adding a unique ID for each relationship, believing that it would force neomodel to create a new relationship rather than overwriting the existing one. But that didn't work either. 
```
class WorkRel(StructuredRel):
    uid = StringProperty(unique=True)
    start_date = DateTimeProperty()
    end_date = DateTimeProperty()
    position = StringProperty() 
```
```
work = RelationshipTo("Company", 'WORKS_AT', model=WorkRel)
```

**Comment by robinedwards** [comment]
Hi @eamonnmag thanks for getting in touch i've just fixed this issue in the latest master and updated the docs.

Can you install from git and confirm it fixes the issue for you?

**Comment by eamonnmag** [comment]
Thanks @robinedwards, this is great! We'll try it out now.

**Comment by eamonnmag** [comment]
Seems good, we just had a python 3 compatibility issue. I made a PR to provide a simple fix.
