### ISSUE TITLE
Doc enhancement: provide comparison with py2neo ogm

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#228]
I think it would be useful to include a comparison of neomodel with py2neo's OGM in the docs. It might help new users and possibly lead to more Neomodel users. Especially since Neomodel does not use Py2neo anymore (right?)

**Comment by robinedwards** [comment]
Yes, perhaps you could come up with a short paragraph? I am not familiar
with it.

**Comment by robinedwards** [comment]
Closing this, if you wish to contribute one I am happy to include it but they are apples and oranges
