### ISSUE TITLE
Can neomodel work with an http connection in v3?

### ISSUE THREAD

**Issue by phoebebright** [robinedwards/neomodel#229]
Having upgrade to neo4j v3 on the server I'm stuck because neomodel is bolt only and I'm on a ubuntu 14.04 server which doesn't natively allow python more than 2.7.6 and I need python 2.7.9 for bolt.  Which piece of software to change/upgrade?   Is it a case of just updating utils.py to allow an http connection or is there something deeper than requires bolt?

**Comment by robinedwards** [comment]
Hi,

I didn't realise neo4j_driver required python 2.7.9 (i guess you meant
that?)

The connection handling stuff is in util.py but i think you might be better
off investing your time in upgrading python. You could use pyenv to install
a more modern version: https://github.com/yyuu/pyenv

Or you  could build it from source on your server:
http://www.renedohmen.nl/blog/2016/10/install-python-2-7-12-on-ubuntu-14-04-lts/

Bolt is considerably faster than the REST interface I'd definitely say its
worth upgrading for.
