### ISSUE TITLE
Make it possible to pass encrypted=False to set_connection

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#230]
I use two instances of Neo4j on my local machine, one for testing, one for experimenting. The trouble is that I often get the error: 

```
neo4j.v1.exceptions.ProtocolError: Server certificate does not match known certificate for 'localhost'; check details in file '/Users/mjm/.neo4j/known_hosts'
```

It is not clear to me how this happens exactly, probably since both servers want to put their autogenerated certificate in the same known_hosts file. It seems that the workaround is using the kwarg encrypted=False in the call to 

```
GraphDatabase.driver('bolt://' + hostname,
                                           auth=basic_auth(username, password),
                                           encrypted=False)
```

So please make it possible to set this in neomodel.db.set_connection

**Comment by adrianicv** [comment]
I've just make a pull request related to this issue, it's waiting to be accepted.

**Comment by mjmare** [comment]
Cool. Thx!

**Comment by robinedwards** [comment]
Merged thanks for this, also added MAX_POOL_SIZE as a config option
