### ISSUE TITLE
Make StructuredNode subscriptable

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#233]
When generating UI it is often useful to iterate over properties. It would be nice to have the StructuredNode be subscriptable, so.

For the moment I have implemented this wit a base class:
```
class SokaNode(StructuredNode):
    # __abstract_node__ = True    # does not work, yields error: AttributeError: type object 'SokaNode' has no attribute '__label__'
    uuid = StringProperty(unique_index=True, default=uuid4)

    def __getitem__(self, item):
        return self.__dict__[item]


class Person(SokaNode):
    first_name = StringProperty()
:
:


p=Person()
print(p['first_name'])

```

**Comment by robinedwards** [comment]
Can you try removing the getitem method to see if thats the cause? I know it does work because i use it in lots of places.

**Comment by mjmare** [comment]
No, the get item is a late addition not related to the abstract_node issue that I encountered earlier, but was reminded when I added the getitem method ;-)

**Comment by robinedwards** [comment]
Which version are you using? I have had a test
for it for quite some time:

https://github.com/robinedwards/neomodel/blob/master/test/test_models.py#L176

I know its not broken in 3.1, pretty sure master works also.
