### ISSUE TITLE
__abstract_node__ does not work

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#234]
I get the error: 
AttributeError: type object 'SokaNode' has no attribute '__label__'

see example:

https://github.com/robinedwards/neomodel/issues/233

**Comment by mjmare** [comment]
My previous report was incomplete. It is the combination of using __abstract_node__  **and** install_all_labels().  I have created an example program illustrating the issue.

```
from uuid import uuid4

from neomodel import IntegerProperty, StringProperty, StructuredNode, config, db, install_all_labels

config.AUTO_INSTALL_LABELS = False
db.set_connection('bolt://neo:neo@localhost:8687')


class SokaNode(StructuredNode):
    __abstract_node__ = True
    uuid = StringProperty(unique_index=True, default=uuid4)


class Person(SokaNode):
    name = StringProperty(unique_index=True)
    age = IntegerProperty(index=True, default=0)


install_all_labels()  # exception raised here.

Person(name='blablabla', age=10).save()
```

Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/neomodel/testit.py", line 19, in <module>
    install_all_labels()
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/venv3/lib/python3.6/site-packages/neomodel/core.py", line 62, in install_all_labels
    install_labels(cls, quiet=False, stdout=stdout)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/venv3/lib/python3.6/site-packages/neomodel/core.py", line 38, in install_labels
    key, cls.__label__, cls.__module__, cls.__name__))
AttributeError: type object 'SokaNode' has no attribute '__label__'
Setting up labels and constraints...

**Comment by robinedwards** [comment]
Aha the full story, you should have posted that earlier. There was no mention of install_labels.

I've just fixed this in master, good spot

**Comment by mjmare** [comment]
I know, me culpa. I was reminded of the problem when reporting #233 ;-)
