### ISSUE TITLE
ArrayProperty of Specific Property

### ISSUE THREAD

**Issue by aaronst** [robinedwards/neomodel#237]
Similarly to https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#arrayfield, I want to be able to define an ArrayProperty using other Properties.  This can be especially useful when choices are involved, such as:

```python
class Conglomerate(StructuredNode):

    sector_choices = ('technology', 'healthcare', 'finance', 'automotive')

    sectors = ArrayProperty(StringProperty(required=True, choices=sector_choices))
```

**Comment by robinedwards** [comment]
Interesting idea, I will look into this, thanks.
