### ISSUE TITLE
when neomodel used along with pysaml2, "test" module causes database cleanup without actually calling any tests

### ISSUE THREAD

**Issue by NecroKote** [robinedwards/neomodel#238]
First of all, thank you Robin for this awesome "battery" !

I've had a problem using your module alongside with **[pysaml2](https://github.com/rohe/pysaml2)**:
when pysaml is imported, it's somehow imports your "test" module, which causes DB cleanup.

I think there is two reason for this:
- test module is installed at top-level (e.g in /lib/site-packages/test)
- database cleanup run's on module import

As a workaround, deleting test from site-packages works for me, but i think there should be a better way.
(maybe move test module to a neomodule itself ? )

PS: I think i should write a ticket to pysaml2, on why do it needs to import every top-level package

**Comment by robinedwards** [comment]
Thanks i believe I need to exclude the tests directory in setup.py. 

packages=find_packages(exclude=("tests",))

It will be in the next release

**Comment by NecroKote** [comment]
Thanks! I hope to see new release soon.

**Comment by robinedwards** [comment]
That's now uploaded to PyPi thanks for spotting that.
