### ISSUE TITLE
Retrieving multiple relationships between the same 2 nodes

### ISSUE THREAD

**Issue by hosford42** [robinedwards/neomodel#239]
I have a situation where it's possible to have multiple relationships of the same type, but with different properties, connecting between the same 2 nodes. Looking through the documentation, it appears that as long as the properties are different, the relationships will be distinct, so the creation side is already handled. But what about retrieving those relationships afterward? The documentation for `RelationshipManager.relationship()` indicates that it returns a single `StructuredRel` object, not an iterable. Is there a way to retrieve the full set of relationships between 2 nodes? A `RelationshipManager.all_relationships()` method, for example?

**Comment by robinedwards** [comment]
Well spotted @hosford42, allowing multiple relationships between nodes is a reasonably recent addition to neomodel this feature got missed!

I will look in to adding a 'all_relationships' method
