### ISSUE TITLE
@hooks for StructuredRel's save()

### ISSUE THREAD

**Issue by aaronst** [robinedwards/neomodel#242]
Would it be possible to add the `@hooks` decorator to `save` for `StructuredRel`?  I know that `delete` is going away but it seems like `save` will be staying, yeah?

**Comment by robinedwards** [comment]
Not sure i follow the hooks decorator is already on save and delete isn't going anywhere.

**Comment by aaronst** [comment]
@robinedwards I think you're confusing `StructuredRel` with `StructuredNode`.  See here: https://github.com/robinedwards/neomodel/blob/master/neomodel/relationship.py#L32

**Comment by aaronst** [comment]
Thank you!
