### ISSUE TITLE
unique_index flag is not working as property parameter

### ISSUE THREAD

**Issue by Brianpan** [robinedwards/neomodel#245]
As I installed neomodel(3.2.1), I set one key as unique_index=True, but the exception of UniqueProperty did not work properly.
Besides, I also ran the test in git repo, and the test_unique() also failed.
 
the following are my part of codes.
```
class Release(StructuredNode):
    ocid = StringProperty(unique_index=True)

r1 = Release(ocid="123").save()
r2 = Release(ocid="123").save()
```

**Comment by robinedwards** [comment]
The tests are passing on Travis. I think you probably forgot to install the labels: http://neomodel.readthedocs.io/en/latest/getting_started.html#setup-constraints-and-indexes

Let me know if this does not fix the problem

**Comment by Brianpan** [comment]
Thanks! I forgot to install labels first.
