### ISSUE TITLE
Could install_all_labels() be boilerplate?

### ISSUE THREAD

**Issue by croccam** [robinedwards/neomodel#247]
Hi,

First of all, congratulations on the library, I find it to be wisely designed, and I have decided to use it for one of my projects! I'm just starting with it, so I hope what I am about to say is not too silly.

Thing is, is it really necessary to call install_all_labels() after each modification/aggregation to the schema? I mean, maybe inside of the __init__ method of StructuredNode a call to install_label() could be placed, so that classes that inherit from it are automatically used as argument to install_label(), and no extra code would be needed.

If I'm just wrong or misunderstood something I would love to know :)

Regards.

**Comment by robinedwards** [comment]
Hi,

Interesting you mention that. It used to do it automatically on class
definition through a meta class. This can and does cause problems for
various use cases web apps using gunicorn for example or people wanting to
mock neomodel. So after much deliberation its now turned off by default.

It can however be turned on there is a setting for it: AUTO_INSTALL_LABELS.
If you look it up in the docs it should be clear.

**Comment by croccam** [comment]
Hi,

I see. That makes sense, my guess was the reason would be something like that.

Thank you very much for your time!
