### ISSUE TITLE
Retrieving relation without properties returns 'None'

### ISSUE THREAD

**Issue by mvanderkroon** [robinedwards/neomodel#248]
Using syntax from the docs such as 

"rel = jim.friends.relationship(bob)"

the "rel" variable is None if the relationship has no associated properties (but does exist). Perhaps change this behaviour so that the existence of the relationship is in fact confirmed (returning a Relationship object with no properties set).

**Comment by robinedwards** [comment]
Good point i am away at the moment but will look into this when I get back.

**Comment by mvanderkroon** [comment]
great, I'll give it a try somewhere this week. Thanks!
