### ISSUE TITLE
Is cardinality declaration on RelationShipFrom really necessary?

### ISSUE THREAD

**Issue by elferia** [robinedwards/neomodel#274]
in [documentation](http://neomodel.readthedocs.io/en/latest/relationships.html#cardinality), 

> Remember this needs to be declared on both sides of the definition

But in [test](https://github.com/robinedwards/neomodel/blob/master/test/test_cardinality.py), there are no cardinality declarations on `RelationShipFrom`.
Is cardinality declaration on `RelationShipFrom` really necessary?

**Comment by robinedwards** [comment]
Yes see my response to the other issue.
