### ISSUE TITLE
How to integrate an existing neo4j database via neomodel?

### ISSUE THREAD

**Issue by mendter** [robinedwards/neomodel#276]
Hello together,

I'm relatively new to neo4j and want to integrate an existing database in django for python with neomodel (django-neomodel).

Can the corresponding node models be derived from the existing neo4j … database? Like inspectdb for relational databases in django.. 

If not, I'm able to write the models myself. Do I need to execute the neomodel_install_labels command afterwards? Because the labels are already there.. 

The thing is I don't want to blow up the existing database.

Thank you! 
Max

**Comment by miguelfg** [comment]
To inform others, this is tackled now with the command `neomodel_inspect_database` included in versions >=5.2.0.
See [docs here](https://neomodel.readthedocs.io/en/latest/getting_started.html#database-inspection-requires-apoc)
