### ISSUE TITLE
Reset constraints on `neomodel_install_labels`

### ISSUE THREAD

**Issue by aanastasiou** [robinedwards/neomodel#280]
`neomodel_install_labels` does not reset constraints and indices prior to execution. Therefore, if a constraint has been removed (in a subsequent revision of the model for example), it is still enforced.

This was discovered after removing a `unique_index` on one of the fields.

Perhaps do a `DROP CONSTRAINT ON . . .` on all constraints and indices by default before installing labels (?). Or maybe even add a parameter for such a reset at will?

*Thanks for neomodel*

**Comment by laky55555** [comment]
Hi, I had similar problem so I did made following [pull request](https://github.com/robinedwards/neomodel/pull/273). I hope it will be merged soon so after it you will be able to call `neomodel_remove_labels` in the same way as `neomodel_install_labels` that will remove all labels. In my version remove it isn't called after installing labels so you will need to do it deliberately when you need it.
